name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    uses: Plasma-Engine/plasma-engine-infra/.github/workflows/lint-test.yml@main
    with:
      python: "[]"
      node: "['20']"

  security:
    uses: Plasma-Engine/plasma-engine-infra/.github/workflows/security-scan.yml@main
    with:
      run_pip_audit: false
